### ISSUE TITLE
kubenetes: invalid image hangs the pipeline

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-runtime#18]

**Comment by tboerger** [comment]
Maybe validate the images before the build?

**Comment by bradrydzewski** [comment]
we validate the image (syntax) but if it does not exist the pipeline seems to freeze. Also I don't think the Pod Create endpoint throws an error if the image does not exist. I think we may need to modify the `Wait` function to handle additional error or event types, but I haven't had the chance to research further.

**Comment by tboerger** [comment]
We could check if the image really exists, without pulling it.

**Comment by bradrydzewski** [comment]
I think the fix might be even simpler. The code is blocking and waiting for kubernetes events, but I think it might need a pod failure event, or something like that:
https://github.com/drone/drone-runtime/blob/kubernetes/engine/kube/kube.go#L129

**Comment by bradrydzewski** [comment]
fixed by https://github.com/drone-runners/drone-runner-kube/pull/6

new kubernetes runner documentation can be found here:
https://kube-runner.docs.drone.io/
