### ISSUE TITLE
docker: implement shmsize

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-runtime#20]

**Comment by snergfdio** [comment]
So will this give me the ability to set
  shm_size: 1024000000
in cloud.drone.io  ?

I see other comments about this existing but it needing 'trusted' flag

**Comment by tboerger** [comment]
I don't know it for sure, but I guess this won't be available on cloud because it can have an massive impact on the build agents.

**Comment by snergfdio** [comment]
well it certainly could depending on what size you set...or if you set a certain size to be max.    Without this option though I'm not sure if there is a way to split the difference.
As in:  its a public repo so it can use the 'free' tier for 90% of the steps.
  But for the couple that need more shm I have a knob to send them towards a paid packet tier.?
