### ISSUE TITLE
docker: implement CPU limits

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-runtime#21]
I could not figure out how to translate kubernetes CPU limits (in string format) to Docker CPU limits. This requires additional research.

**Comment by tboerger** [comment]
You can easily translate the strings to integers

**Comment by bradrydzewski** [comment]
I think Docker and Kubernetes use different measurements. So we just need to figure out how to translate those measurements correctly.

**Comment by tboerger** [comment]
But this should be a simple formula to translate.

**Comment by zetaab** [comment]
See https://github.com/drone/drone-runtime/pull/29#issuecomment-446681972 when impelementing limits for docker. In case of docker limits are only implemented not requests.
