### ISSUE TITLE
Allow user specified ttlSecondsAfterFinished

### ISSUE THREAD

**Issue by flah00** [drone/drone-runtime#28]
When drone-server creates a kubernetes [job](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#clean-up-finished-jobs-automatically), provide users with the ability to define  `ttlSecondsAfterFinished`.

**Comment by bradrydzewski** [comment]
this is configurable using the `DRONE_KUBERNETES_TTL_AFTER_FINISHED` variable which should be set to the number of seconds. The default is `DRONE_KUBERNETES_TTL_AFTER_FINISHED=300`
