### ISSUE TITLE
Can't go get on MacOS

### ISSUE THREAD

**Issue by Kryan90** [drone/drone-runtime#30]
I am unable to install the drone-runtime on MacOS.
The issue is with a vendor library, but I figured I should point it out here.
```
go get -u github.com/drone/drone-runtime
# docker.io/go-docker
../../../docker.io/go-docker/service_create.go:128:36: cannot use dgst (type "github.com/opencontainers/go-digest".Digest) as type "github.com/docker/distribution/vendor/github.com/opencontainers/go-digest".Digest in argument to reference.WithDigest```

**Comment by tboerger** [comment]
How should drone be able to solve the vendoring issue of the vendored dependency?

**Comment by Kryan90** [comment]
No idea. I wasn't suggesting it was something drone needed to fix.
