### ISSUE TITLE
kubernetes: Configmap is mounted to home as directory

### ISSUE THREAD

**Issue by Shegox** [drone/drone-runtime#31]
When executing a step, the kubernetes runtime mounts f.e. the .netrc file to the /root/ directory. This causes the whole /root/* to be read-only. 

This can be resolved with using a subpath to mount only the specific file from the configmap. 

This can result in errors like these when using node: 
```
+ + npm i
npm ERR! path /root/.npm
npm ERR! code EROFS npm ERR! errno -30 npm ERR! syscall mkdir npm ERR! rofs EROFS: read-only file system, mkdir '/root/.npm' npm ERR! rofs Often virtualized file systems, or other file systems npm ERR! rofs that don't support symlinks, give this error.
```

**Comment by paulreimer** [comment]
I can confirm this issue -- I'm unable to use the [drone-serverless](https://github.com/giusedroid/drone-serverless) plugin, as the `sls` executable attempts to create a dotfile in `/root` upon first run.

**Comment by Shegox** [comment]
hey @paulreimer, 
a quick fix you try is overriding the $HOME env variable. Some tools (gcloud, npm, docker) use them to determine where to create a dotfile. Something like the below solved the problem temporarily for me. 

```
- name: container-build-push
  image: plugins/docker
  privileged: true
  settings:
    repo: eu.gcr.io/test
    registry: eu.gcr.io
    tag: ${DRONE_BUILD_NUMBER}   
    password:
      from_secret: google_credentials
    username: _json_key
    debug: true
  environment:
    HOME: "/tmp"
```

**Comment by bradrydzewski** [comment]
fixed by https://github.com/drone/drone-yaml/commit/1e125e10a9c8c290de8ca6a05428f38ec8be97db
