### ISSUE TITLE
Make Log Limit Configurable

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-runtime#33]
The log limit is hard-coded to 5mb. Make this configurable and perhaps default to a lower level.

**Comment by jm4games** [comment]
PR for doing this #78

**Comment by sheinbergon** [comment]
@bradrydzewski Any news on this?

**Comment by tboerger** [comment]
drone-runtime is deprecated in favor of the runners implementations. Beside that, if there is any progress on that you would read it within this issue.
