### ISSUE TITLE
Kubernetes: 'cannot create log'

### ISSUE THREAD

**Issue by everflux** [drone/drone-runtime#39]
I think this might be a bug.
I am using the kubernetes executor on ARM64 using cri-o runtime.
Drone creates a job and the log from the 'drone-controller' reports

```
1 client_config.go:548] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
log: exiting because of error: log: cannot create log: open /tmp/drone-controller.drone-job-wgfkw-45jr6.unknownuser.log.WARNING.20190117-211751.1: no such file or directory 
```

Assumption: Could the /tmp directory be missing?

I noticed that the AMD64 image is using alpine as base image while ARM64 uses drone/ca-certs.

**Comment by bradrydzewski** [comment]
thanks for the report, I just updated arm and arm64 Docker images to use alpine
