### ISSUE TITLE
Add a prefix to the auto-generated resources by the pipeline controller

### ISSUE THREAD

**Issue by exwyezed** [drone/drone-runtime#52]
Currently the auto-generated resources name by the pipeline controller looks like this: `n3grlskg6s9ac7c39l5dt80i49iirtue`. It makes extremely hard to monitoring them as we never can expect how they will looks like.

Example screenshot:
<img width="500" alt="screen shot 2019-03-05 at 4 59 17 am" src="https://user-images.githubusercontent.com/9363272/53780180-7280b480-3f03-11e9-9239-40df95da26e1.png">

Adding a prefix to the auto-generated Namespace and Pod would solve this.

**Comment by bradrydzewski** [comment]
fixed by https://github.com/drone-runners/drone-runner-kube/commit/f090cae63804a853990447acae6e5a6843c2ca02

new kubernetes runner documentation can be found here:
https://kube-runner.docs.drone.io/
