### ISSUE TITLE
Allow to set DRONE_RUNNER_LABELS on kubernetes jobs

### ISSUE THREAD

**Issue by max-lobur** [drone/drone-runtime#63]
When using kubernetes mode there's no way to pass DRONE_RUNNER_LABELS onto jobs, thus I can't use https://docs.drone.io/config/pipeline/nodes/ feature

My current use case: I have drone servers in dev & prod, both watching the same repo. I want dev server to execute dev deploy part of the yaml, and prod - prod. If I could pass DRONE_RUNNER_LABELS to drone server, which passes them down to all jobs->pods, I could ensure I have differently labeled workers in dev/prod and use filtering

Longterm: DRONE_RUNNER_LABELS itself might not be suitable for k8s at all, as k8s provides own scheduling techniques. Instead of using runner labels to separate environments, maybe it makes sense to add a separate server var for this .

**Comment by bradrydzewski** [comment]
DRONE_RUNNER_LABELS is only used for agents+docker (not kubernetes) to enable the equivalent of node selectors. With Kubernetes, you can use `nodes` because the `nodes` block is translated directly to node selector syntax. See https://github.com/drone/drone/blob/master/scheduler/kube/kube.go#L141

**Comment by max-lobur** [comment]
Interesting, thanks! Will check if I can use that

**Comment by max-lobur** [comment]
@bradrydzewski if I filter based on k8s nodes here, this will give me a hanging build on a drone server of the 2nd env every time.

What would you suggest to route builds between different drone instances? (see my use case)

**Comment by max-lobur** [comment]
Platform would work but again no way to set on drone server...

**Comment by max-lobur** [comment]
asked on SO https://stackoverflow.com/questions/55475623/drone-self-hosted-pipeline-routing-between-drone-servers

**Comment by max-lobur** [comment]
From Gitter:
```
I recommend using .drone.yml for prod, and then creating a .drone.dev.yml for dev. 
In your dev Drone instance, in the repository settings, point Drone at the .drone.dev.yml
```
