### ISSUE TITLE
kubernetes: support resource qutoas

### ISSUE THREAD

**Issue by max-lobur** [drone/drone-runtime#66]
We faced an issue where 2 simultaneous builds started on same k8s node and drained CPU very quickly, which caused evictions.

Would be great to have a support for resource requests & quotas https://kubernetes.io/docs/concepts/policy/resource-quotas/ per namespace, at least on drone configuration level - same for all builds. This would allow kubernetes scheduler to place builds more carefully.

**Comment by bradrydzewski** [comment]
there is a new (still experimental) kubernetes runner available.  This iteration does not create custom namespaces per pipeline, which should solve the underlying issue that Drone this feature request. https://github.com/drone-runners/drone-runner-kube
