### ISSUE TITLE
bug: unable to cancel

### ISSUE THREAD

**Issue by stevecrozz** [drone/drone-runtime#71]
I managed to boil my issue down to the smallest possible failure scenario. Here is a minimal example:
https://github.com/stevecrozz/drone-issues/tree/cannot-cancel-with-depends_on

While the second step is running, I decide to cancel the build from the drone UI. The drone UI and the drone database is updated, the drone agent receives the cancel message, but the docker container that is running the build step does not exit. 

I'm running drone using dockerhub images:
- drone/drone:1.1.0
- drone/agent:1.1.0

**Comment by GCorbel** [comment]
@stevecrozz Did you found a solution to this issue? How do you know the agent received the message?

I saw than the payload of the DELETE request send to the server say than the process is killed but it isn't.

**Comment by GCorbel** [comment]
I tried to do something similar, with curl, to what's drone is supposed to do : 

```
docker-compose exec drone-agent curl --unix-socket /var/run/docker.sock -X POST http://v.1.24/containers/af0c5571da00/kill
```

It killed the container correctly so the problem doesn't comes from the communication the agent and the socket.

**Comment by GCorbel** [comment]
I confirm the signal is received by the agent. There is a "done listening for cancel signals". It probably comes from [this line](https://github.com/drone/drone/blob/master/operator/runner/runner.go#L605). It should goes in the first condition of the `if` and trigger the `cancel` method.

**Comment by stevecrozz** [comment]
fwiw: I did not find an answer and developed a terrible system of hacks using shell scripts and cron jobs to work around this problem

**Comment by GCorbel** [comment]
Can you share your hack?

**Comment by stevecrozz** [comment]
I don't mind, but it is very specific to my own implementation. I use an ec2 instance per pipeline in my environment and the hack involves shutting down the instance when it gets into this state. If you're still interested, I can dig up the cron job...

**Comment by GCorbel** [comment]
I still can check what it is. I can give me some ideas.

The solution I think at the moment is to watch logs and do a `docker-compose restart` when there is "done listening for cancel signals" in it.

**Comment by bradrydzewski** [comment]
this is no longer an issue in the newer `drone/drone-runner-*` images which replace the `drone/agent` containers.
