### ISSUE TITLE
DRONE_KUBERNETES_TTL_AFTER_FINISHED

### ISSUE THREAD

**Issue by Sluggerman** [drone/drone-runtime#79]
Hi, 

According to https://github.com/drone/drone-runtime/issues/28, I should be able to set the above variable in drone server (running kubernetes native mode), however when I add it to drone server as an environment variable, it does not propagate to build jobs.

Please advise.

**Comment by Sluggerman** [comment]
Hello @bradrydzewski , could you please advise if that env variable is still valid and where to set it up? Thanks

**Comment by bradrydzewski** [comment]
the kubernetes implementation in this repository was scrapped for reasons described [here](https://github.com/drone/drone-runtime/issues/69). We have a new implementation, created from scratch, that no longer uses jobs which means this question no longer applies. New codebase can be found here: https://github.com/drone-runners/drone-runner-kube
