### ISSUE TITLE
[feature] support custom volume to mapping source-code when use k8s mode

### ISSUE THREAD

**Issue by 9nix00** [drone/drone-runtime#82]
Dear all,

Drone is an awesome CI/CD tool and we use it about 3 years. thanks again !
recently, we upgrade our workflow to work with Drone k8s build feature.

but we found it's a little slow because when use k8s mode, drone-runner-pod always create a new volume mapping because pod and namespace name is random value.it's make sense. we should physical isolation different pod.

but I think maybe we can set a volume to mapping source-code & only for source-code. all pod work on same k8s node will share same path. this can save a lot of time.

**Comment by bradrydzewski** [comment]
please note that we are not currently investing any time in the experimental kubernetes runner, which was deprecated in April.  We will consider this feedback for our second iteration attempt. See https://github.com/drone/drone-runtime/issues/69

**Comment by 9nix00** [comment]
Sorry, I post a wrong place,  auto-completion browser address. lol.
closed it.

**Comment by bradrydzewski** [comment]
I moved the issue here, from `drone/drone`.  This is the appropriate place for the issue, but the kubernetes runner is deprecated, and is not being actively developed at this time.
